'1', 'Parasitology'
'2', 'Microbiology'
'3', 'Haematology'
'4', 'Serology'
'5', 'Blood Bank' 
'6', 'Lab Reception'
'7', 'Biochemistry' 
'8', 'Flow Cytometry'
'9', 'DNA/PCR'
'10', 'Immunochemistry'
'11', 'Paediatric Lab '